---
- name: "Installing Patroni ETCD Postgresql15 On RHEL-like Distro"
  ansible.builtin.dnf:
    name:
      - haproxy
    state: present
  when: ansible_facts['os_family'] == "RedHat" or
        ansible_facts['os_family'] == "RED"

- name: "Installing Patroni On Debian-like Distro"
  ansible.builtin.apt:
    name:
      - haproxy
    state: present
  when: ansible_facts['os_family'] == "Debian" or
        ansible_facts['os_family'] == "Astra Linux"

- name: "Configuring haproxy"
  ansible.builtin.template:
    src: 'haproxy.cfg.j2'
    dest: /etc/haproxy/haproxy.cfg
    backup: true
    owner: root
    group: root
    mode: '0644'

- name: "Starting haproxy service"
  ansible.builtin.systemd:
    name: haproxy.service
    state: restarted
    enabled: true
