---
- name: "Preparing hosts, checking available repositories, setting local repositories if needed"
  hosts: etcd
  become: true
  gather_facts: true
  roles:
    - role: ready_hosts
    - role: repos

- name: "Installing required packages"
  hosts: patroni_hosts
  become: true
  gather_facts: true
  roles:
    - role: pkgs

# --- SSL сначала генерим на локальной машине
- name: "Generate SSL certificates"
  hosts: all_hosts
  gather_facts: false
  become: true
  roles:
    - role: ssl


- name: "Installing and Creating Etcd Cluster"
  hosts: etcd
  become: true
  gather_facts: true
  roles:
    - role: etcd

- name: "Installing and Creating Patroni Cluster"
  hosts: patroni_hosts
  become: true
  gather_facts: true
  roles:
    - role: patroni

- name: "Installing Haproxy"
  hosts: patroni_hosts
  become: true
  gather_facts: true
  roles:
    - role: haproxy

- name: "Installing Keepalived"
  hosts: patroni_hosts
  become: true
  gather_facts: true
  roles:
    - role: keepalived

- name: "Restarting Services"
  hosts: all_hosts
  become: true
  gather_facts: true
  roles:
    - role: services_restart
