# - name: "Installing And Creating Patroni Cluster"
#   hosts: all_hosts
#   become: true
#   gather_facts: true
#   roles:
#     - role: ssl

- name: "Installing And Creating Patroni Cluster"
  hosts: etcd
  become: true
  gather_facts: true
  roles:
    - role: etcd

- name: "Installing And Creating Patroni Cluster"
  hosts: all_hosts
  become: true
  gather_facts: true
  roles:
    - role: services_restart

  