---
- name: "Create SSL directory structure"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ ssl_root_dir }}"
    - "{{ ssl_etcd_dir }}"
    - "{{ ssl_patroni_dir }}"
    - "{{ ssl_haproxy_dir }}"

- name: "Generate CA private key"
  community.crypto.openssl_privatekey:
    path: "{{ ssl_ca_privatekey_path }}"

- name: "Generate CA CSR"
  community.crypto.openssl_csr:
    path: "{{ ssl_ca_csr_path }}"
    privatekey_path: "{{ ssl_ca_privatekey_path }}"
    country_name: "{{ ssl_subject_country_name }}"
    state_or_province_name: "{{ ssl_subject_state_or_province_name }}"
    locality_name: "{{ ssl_subject_locality_name }}"
    organization_name: "{{ ssl_subject_organization_name }}"
    organizational_unit_name: "{{ ssl_subject_organizational_unit_name }}"
    common_name: "{{ ssl_ca_common_name }}"
    basic_constraints:
      - CA:TRUE
      - pathlen:1
    basic_constraints_critical: true
    key_usage:
      - keyCertSign
      - digitalSignature

- name: "Generate CA certificate"
  community.crypto.x509_certificate:
    path: "{{ ssl_ca_cert_path }}"
    privatekey_path: "{{ ssl_ca_privatekey_path }}"
    csr_path: "{{ ssl_ca_csr_path }}"
    provider: selfsigned
