---
- name: "Generate etcd private keys"
  community.crypto.openssl_privatekey:
    path: "{{ ssl_etcd_dir }}/{{ item }}.pem"
  loop: "{{ groups['etcd'] }}"

- name: "Generate etcd CSRs"
  community.crypto.openssl_csr:
    path: "{{ ssl_etcd_dir }}/{{ item }}.csr"
    privatekey_path: "{{ ssl_etcd_dir }}/{{ item }}.pem"
    country_name: "{{ ssl_subject_country_name }}"
    state_or_province_name: "{{ ssl_subject_state_or_province_name }}"
    locality_name: "{{ ssl_subject_locality_name }}"
    organization_name: "{{ ssl_subject_organization_name }}"
    organizational_unit_name: "{{ ssl_subject_organizational_unit_name }}"
    common_name: "{{ item }}"
    key_usage:
      - digitalSignature
    extended_key_usage:
      - serverAuth
      - clientAuth
    subject_alt_name:
      - DNS:{{ item }}
      - IP:{{ hostvars[item]['ansible_host'] }}
      - IP:127.0.0.1
  loop: "{{ groups['etcd'] }}"

- name: "Generate etcd certificates"
  community.crypto.x509_certificate:
    path: "{{ ssl_etcd_dir }}/{{ item }}.crt"
    privatekey_path: "{{ ssl_etcd_dir }}/{{ item }}.pem"
    csr_path: "{{ ssl_etcd_dir }}/{{ item }}.csr"
    ownca_path: "{{ ssl_ca_cert_path }}"
    ownca_privatekey_path: "{{ ssl_ca_privatekey_path }}"
    provider: ownca
  loop: "{{ groups['etcd'] }}"
