ssl_root_dir: "{{ playbook_dir }}/ssl"
ssl_etcd_dir: "{{ ssl.root_dir }}/etcd"
ssl_patroni_dir: "{{ ssl.root_dir }}/patroni"
ssl_haproxy_dir: "{{ ssl.root_dir }}/haproxy"


ssl_ca_privatekey_path: "{{ ssl.root_dir }}/ca-key.pem"
ssl_ca_csr_path: "{{ ssl.root_dir }}/ca.csr"
ssl_ca_cert_path: "{{ ssl.root_dir }}/ca-cert.pem"
ssl_ca_common_name: "Cluster-CA"


ssl_subject_country_name: "RU"
ssl_subject_state_or_province_name: "Moscow"
ssl_subject_locality_name: "Moscow"
ssl_subject_organization_name: "MyOrg"
ssl_subject_organizational_unit_name: "DBA"

# Куда класть на хостах

ssl_host_dest_etcd: /etc/etcd/ssl
ssl_host_dest_patroni: /etc/patroni/ssl
ssl_host_dest_haproxy: /etc/haproxy/ssl
